runtime: python312

# Environment variables
env_variables:
  FLASK_ENV: 'production'
  SECRET_KEY: 'production-secret-key-change-immediately'
  
# Handlers
handlers:
- url: /static
  static_dir: static
  secure: always

- url: /css
  static_dir: css
  secure: always

- url: /js
  static_dir: js
  secure: always

- url: /images
  static_dir: images
  secure: always

- url: /.*
  script: auto
  secure: always

# Instance configuration
instance_class: F2

automatic_scaling:
  target_cpu_utilization: 0.65
  min_instances: 1
  max_instances: 10
