runtime: python312

# Environment variables
env_variables:
  FLASK_ENV: 'production'
  SECRET_KEY: 'b8d9ee9301389d26f9d3c22afac53a9c2648ce219972d2503f6e7fe7ecd25db5'
  # Email Configuration - Gmail SMTP
  SMTP_HOST: 'smtp.gmail.com'
  SMTP_PORT: '587'
  SMTP_USERNAME: 'yinglu08fall@gmail.com'
  SMTP_PASSWORD: 'bdtfwnjvrqdlnajf'
  FROM_EMAIL: 'yinglu08fall@gmail.com'
  ADMIN_EMAIL: 'yinglu08fall@gmail.com'
  
# Handlers
handlers:
- url: /static
  static_dir: static
  secure: always

- url: /css
  static_dir: css
  secure: always

- url: /js
  static_dir: js
  secure: always

- url: /images
  static_dir: images
  secure: always

- url: /.*
  script: auto
  secure: always

# Instance configuration
instance_class: F2

automatic_scaling:
  target_cpu_utilization: 0.65
  min_instances: 1
  max_instances: 10
